version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    container_name: jwtauth
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
